# Generated by Django 2.2.16 on 2023-08-05 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20230804_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата комментирования'),
            preserve_default=False,
        ),
    ]
